apiVersion: v1
kind: Service
metadata:
  name: stackfood-db
  labels:
    app: stackfood-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: stackfood-db
