apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stackfood-db
  labels:
    app.kubernetes.io/name: stackfood-db
    app.kubernetes.io/instance: stackfood-db
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: stackfood
    app.kubernetes.io/managed-by: argocd
    app: stackfood-db
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  serviceName: stackfood-db
  replicas: 1
  selector:
    matchLabels:
      app: stackfood-db
  template:
    metadata:
      labels:
        app: stackfood-db
    spec:
      containers:
        - name: postgres
          image: postgres:15.3-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: stackfood-db-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: stackfood-db-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stackfood-db-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: init-scripts
          configMap:
            name: stackfood-db-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
