apiVersion: v1
kind: Service
metadata:
  name: stackfood-api
  labels:
    app: stackfood-api
spec:
  type: ClusterIP
  ports:
    - port: 5039
      targetPort: 5039
      protocol: TCP
      name: http
    - port: 7189
      targetPort: 7189
      protocol: TCP
      name: https
  selector:
    app: stackfood-api
