apiVersion: v1
kind: Service
metadata:
  name: stackfood-api
  labels:
    app: stackfood-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: stackfood-api
