apiVersion: apps/v1
kind: Deployment
metadata:
  name: stackfood-worker
  labels:
    app.kubernetes.io/name: stackfood-worker
    app.kubernetes.io/instance: stackfood-worker
    app.kubernetes.io/component: worker
    app.kubernetes.io/part-of: stackfood
    app.kubernetes.io/managed-by: argocd
    app: stackfood-worker
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stackfood-worker
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stackfood-worker
    spec:
      containers:
      - name: worker
        image: ghcr.io/stack-food/stackfood-worker:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: stackfood-config
        - secretRef:
            name: stackfood-secrets