apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackfood

resources:
  - ../base
  - configmap.yaml
  - secret.yaml
  - ghcr-secret.yaml
  - postgres-service.yaml

patchesStrategicMerge:
  - patch-deployment.yaml

images:
  - name: ghcr.io/stack-food/stackfood-api/worker
    newTag: master
