apiVersion: v1
kind: Service
metadata:
  name: stackfood-db-external
  namespace: stackfood-dev
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30432 # Porta no range 30000-32767
  selector:
    app: stackfood-db
