apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stackfood-api-master
  namespace: ${namespace}
  labels:
    app.kubernetes.io/name: stackfood-api
    app.kubernetes.io/part-of: stackfood
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: terraform
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: ${project_name}

  source:
    repoURL: ${source_repo_url}
    targetRevision: ${target_revision}
    path: k8s/api/prod

  destination:
    server: ${destination_server}
    namespace: ${api_namespace}

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas

  revisionHistoryLimit: 10

  info:
    - name: Description
      value: StackFood API - Production Environment
    - name: Environment
      value: Production
    - name: Branch
      value: ${target_revision}
